name: Deployment Pipeline

on:
  push:
    branches: ['main']

jobs: Deploy pipeline
  runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Run cypress test
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run
          start: npm run start
          wait-on: http://localhost:3000