name: "Test GH action"

on:
  push:
    branches: ['main']

jobs:
  main-push-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
      - name: Get date
        run: echo "the date is $(date)"
      - name: see github context
        run: echo "${{ toJson(github) }}"