name: "Test GH action"

on:
  push:
    branches: ['main']

jobs:
  main-push-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
      - name: Get date
        run: `the date is ${date}`